version: "3.7"

services:
  product-service:
    ports:
      - "3000-3001:${SERVICE_PORT}"
    build:
      context: ./
      dockerfile: docker/product-service/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped

  review-processing-service:
    ports:
      - "4000-4001:${SERVICE_PORT}"
    build:
      context: ./
      dockerfile: docker/review-processing-service/Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - product-service
      - review-processing-service
    ports:
      - "80:80"
